# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 05:13
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True)),
                ('img_url', models.CharField(max_length=512)),
                ('prep_time', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=2)),
                ('servings', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=2)),
                ('direction', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
