# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=uuid.uuid1, max_length=100, unique=True),
        ),
    ]
