# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 08:39
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('product', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='direction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=2),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=2),
        ),
        migrations.AddField(
            model_name='product',
            name='recipes',
            field=models.ManyToManyField(to='products.Recipe'),
        ),
    ]
