# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170323_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=uuid.uuid1, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='img_url',
            field=models.CharField(max_length=1512),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=2512, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(max_length=115),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.CharField(max_length=201),
        ),
    ]
