# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 01:34
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=1000)),
                ('order', models.CharField(max_length=4000)),
                ('f_name', models.CharField(max_length=500)),
                ('l_name', models.CharField(max_length=500)),
                ('s_address', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
